---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: code-distributor
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: code-distributor
rules:
- apiGroups: [""]
  resources: ["namespaces", "configmaps", "workshopsessions"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "create", "update", "patch"]
- apiGroups: ["training.eduk8s.io"]
  resources: ["workshopsessions"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: code-distributor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: code-distributor
subjects:
  - kind: ServiceAccount
    name: code-distributor
    namespace: default
